/*
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * MainMatch
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-29T03:59:18.387-05:00")
public class MainMatch {
  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("deletedAt")
  private String deletedAt = null;

  @SerializedName("duration")
  private Integer duration = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("lastTimeAlive")
  private Integer lastTimeAlive = null;

  @SerializedName("timeEnd")
  private Integer timeEnd = null;

  @SerializedName("timeStart")
  private Integer timeStart = null;

  @SerializedName("updatedAt")
  private String updatedAt = null;

  public MainMatch createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public MainMatch deletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
    return this;
  }

   /**
   * Get deletedAt
   * @return deletedAt
  **/
  @ApiModelProperty(value = "")
  public String getDeletedAt() {
    return deletedAt;
  }

  public void setDeletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
  }

  public MainMatch duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @ApiModelProperty(value = "")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public MainMatch id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public MainMatch lastTimeAlive(Integer lastTimeAlive) {
    this.lastTimeAlive = lastTimeAlive;
    return this;
  }

   /**
   * Get lastTimeAlive
   * @return lastTimeAlive
  **/
  @ApiModelProperty(value = "")
  public Integer getLastTimeAlive() {
    return lastTimeAlive;
  }

  public void setLastTimeAlive(Integer lastTimeAlive) {
    this.lastTimeAlive = lastTimeAlive;
  }

  public MainMatch timeEnd(Integer timeEnd) {
    this.timeEnd = timeEnd;
    return this;
  }

   /**
   * Get timeEnd
   * @return timeEnd
  **/
  @ApiModelProperty(value = "")
  public Integer getTimeEnd() {
    return timeEnd;
  }

  public void setTimeEnd(Integer timeEnd) {
    this.timeEnd = timeEnd;
  }

  public MainMatch timeStart(Integer timeStart) {
    this.timeStart = timeStart;
    return this;
  }

   /**
   * Get timeStart
   * @return timeStart
  **/
  @ApiModelProperty(value = "")
  public Integer getTimeStart() {
    return timeStart;
  }

  public void setTimeStart(Integer timeStart) {
    this.timeStart = timeStart;
  }

  public MainMatch updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MainMatch mainMatch = (MainMatch) o;
    return Objects.equals(this.createdAt, mainMatch.createdAt) &&
        Objects.equals(this.deletedAt, mainMatch.deletedAt) &&
        Objects.equals(this.duration, mainMatch.duration) &&
        Objects.equals(this.id, mainMatch.id) &&
        Objects.equals(this.lastTimeAlive, mainMatch.lastTimeAlive) &&
        Objects.equals(this.timeEnd, mainMatch.timeEnd) &&
        Objects.equals(this.timeStart, mainMatch.timeStart) &&
        Objects.equals(this.updatedAt, mainMatch.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, deletedAt, duration, id, lastTimeAlive, timeEnd, timeStart, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MainMatch {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastTimeAlive: ").append(toIndentedString(lastTimeAlive)).append("\n");
    sb.append("    timeEnd: ").append(toIndentedString(timeEnd)).append("\n");
    sb.append("    timeStart: ").append(toIndentedString(timeStart)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

