/*
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ModelGameComponent
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-25T01:07:09.701808-04:00[America/Toronto]")public class ModelGameComponent {

  @SerializedName("angle")
  private Integer angle = null;

  @SerializedName("codes")
  private List<ModelCode> codes = null;

  @SerializedName("configs")
  private List<ModelConfig> configs = null;

  @SerializedName("gameDefinition")
  private Integer gameDefinition = null;

  @SerializedName("gunAngle")
  private Integer gunAngle = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("isNPC")
  private Boolean isNPC = null;

  @SerializedName("life")
  private Integer life = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("userID")
  private Integer userID = null;

  @SerializedName("x")
  private Integer x = null;

  @SerializedName("y")
  private Integer y = null;
  public ModelGameComponent angle(Integer angle) {
    this.angle = angle;
    return this;
  }

  

  /**
  * Get angle
  * @return angle
  **/
  @Schema(description = "")
  public Integer getAngle() {
    return angle;
  }
  public void setAngle(Integer angle) {
    this.angle = angle;
  }
  public ModelGameComponent codes(List<ModelCode> codes) {
    this.codes = codes;
    return this;
  }

  public ModelGameComponent addCodesItem(ModelCode codesItem) {
    if (this.codes == null) {
      this.codes = new ArrayList<ModelCode>();
    }
    this.codes.add(codesItem);
    return this;
  }

  /**
  * Get codes
  * @return codes
  **/
  @Schema(description = "")
  public List<ModelCode> getCodes() {
    return codes;
  }
  public void setCodes(List<ModelCode> codes) {
    this.codes = codes;
  }
  public ModelGameComponent configs(List<ModelConfig> configs) {
    this.configs = configs;
    return this;
  }

  public ModelGameComponent addConfigsItem(ModelConfig configsItem) {
    if (this.configs == null) {
      this.configs = new ArrayList<ModelConfig>();
    }
    this.configs.add(configsItem);
    return this;
  }

  /**
  * Get configs
  * @return configs
  **/
  @Schema(description = "")
  public List<ModelConfig> getConfigs() {
    return configs;
  }
  public void setConfigs(List<ModelConfig> configs) {
    this.configs = configs;
  }
  public ModelGameComponent gameDefinition(Integer gameDefinition) {
    this.gameDefinition = gameDefinition;
    return this;
  }

  

  /**
  * Get gameDefinition
  * @return gameDefinition
  **/
  @Schema(description = "")
  public Integer getGameDefinition() {
    return gameDefinition;
  }
  public void setGameDefinition(Integer gameDefinition) {
    this.gameDefinition = gameDefinition;
  }
  public ModelGameComponent gunAngle(Integer gunAngle) {
    this.gunAngle = gunAngle;
    return this;
  }

  

  /**
  * Get gunAngle
  * @return gunAngle
  **/
  @Schema(description = "")
  public Integer getGunAngle() {
    return gunAngle;
  }
  public void setGunAngle(Integer gunAngle) {
    this.gunAngle = gunAngle;
  }
  public ModelGameComponent id(Integer id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }
  public ModelGameComponent isNPC(Boolean isNPC) {
    this.isNPC = isNPC;
    return this;
  }

  

  /**
  * Get isNPC
  * @return isNPC
  **/
  @Schema(description = "")
  public Boolean isIsNPC() {
    return isNPC;
  }
  public void setIsNPC(Boolean isNPC) {
    this.isNPC = isNPC;
  }
  public ModelGameComponent life(Integer life) {
    this.life = life;
    return this;
  }

  

  /**
  * Get life
  * @return life
  **/
  @Schema(description = "")
  public Integer getLife() {
    return life;
  }
  public void setLife(Integer life) {
    this.life = life;
  }
  public ModelGameComponent name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public ModelGameComponent userID(Integer userID) {
    this.userID = userID;
    return this;
  }

  

  /**
  * Get userID
  * @return userID
  **/
  @Schema(description = "")
  public Integer getUserID() {
    return userID;
  }
  public void setUserID(Integer userID) {
    this.userID = userID;
  }
  public ModelGameComponent x(Integer x) {
    this.x = x;
    return this;
  }

  

  /**
  * Get x
  * @return x
  **/
  @Schema(description = "")
  public Integer getX() {
    return x;
  }
  public void setX(Integer x) {
    this.x = x;
  }
  public ModelGameComponent y(Integer y) {
    this.y = y;
    return this;
  }

  

  /**
  * Get y
  * @return y
  **/
  @Schema(description = "")
  public Integer getY() {
    return y;
  }
  public void setY(Integer y) {
    this.y = y;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelGameComponent modelGameComponent = (ModelGameComponent) o;
    return Objects.equals(this.angle, modelGameComponent.angle) &&
        Objects.equals(this.codes, modelGameComponent.codes) &&
        Objects.equals(this.configs, modelGameComponent.configs) &&
        Objects.equals(this.gameDefinition, modelGameComponent.gameDefinition) &&
        Objects.equals(this.gunAngle, modelGameComponent.gunAngle) &&
        Objects.equals(this.id, modelGameComponent.id) &&
        Objects.equals(this.isNPC, modelGameComponent.isNPC) &&
        Objects.equals(this.life, modelGameComponent.life) &&
        Objects.equals(this.name, modelGameComponent.name) &&
        Objects.equals(this.userID, modelGameComponent.userID) &&
        Objects.equals(this.x, modelGameComponent.x) &&
        Objects.equals(this.y, modelGameComponent.y);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(angle, codes, configs, gameDefinition, gunAngle, id, isNPC, life, name, userID, x, y);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelGameComponent {\n");
    
    sb.append("    angle: ").append(toIndentedString(angle)).append("\n");
    sb.append("    codes: ").append(toIndentedString(codes)).append("\n");
    sb.append("    configs: ").append(toIndentedString(configs)).append("\n");
    sb.append("    gameDefinition: ").append(toIndentedString(gameDefinition)).append("\n");
    sb.append("    gunAngle: ").append(toIndentedString(gunAngle)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isNPC: ").append(toIndentedString(isNPC)).append("\n");
    sb.append("    life: ").append(toIndentedString(life)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    userID: ").append(toIndentedString(userID)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
