/*
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ModelBulkConfig
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-04T21:21:42.311875-05:00[America/Toronto]")public class ModelBulkConfig {

  @SerializedName("configs")
  private List<ModelConfig> configs = null;
  public ModelBulkConfig configs(List<ModelConfig> configs) {
    this.configs = configs;
    return this;
  }

  public ModelBulkConfig addConfigsItem(ModelConfig configsItem) {
    if (this.configs == null) {
      this.configs = new ArrayList<ModelConfig>();
    }
    this.configs.add(configsItem);
    return this;
  }

  /**
  * Get configs
  * @return configs
  **/
  @Schema(description = "")
  public List<ModelConfig> getConfigs() {
    return configs;
  }
  public void setConfigs(List<ModelConfig> configs) {
    this.configs = configs;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelBulkConfig modelBulkConfig = (ModelBulkConfig) o;
    return Objects.equals(this.configs, modelBulkConfig.configs);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(configs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelBulkConfig {\n");
    
    sb.append("    configs: ").append(toIndentedString(configs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
