/*
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/**
 * ModelDefaultState
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-05-31T12:20:23.222-04:00[America/Toronto]")public class ModelDefaultState {

  @SerializedName("angle")
  private Integer angle = null;

  @SerializedName("gunAngle")
  private Integer gunAngle = null;

  @SerializedName("life")
  private Integer life = null;

  @SerializedName("x")
  private Integer x = null;

  @SerializedName("y")
  private Integer y = null;
  public ModelDefaultState angle(Integer angle) {
    this.angle = angle;
    return this;
  }

  

  /**
  * Get angle
  * @return angle
  **/
  @Schema(description = "")
  public Integer getAngle() {
    return angle;
  }
  public void setAngle(Integer angle) {
    this.angle = angle;
  }
  public ModelDefaultState gunAngle(Integer gunAngle) {
    this.gunAngle = gunAngle;
    return this;
  }

  

  /**
  * Get gunAngle
  * @return gunAngle
  **/
  @Schema(description = "")
  public Integer getGunAngle() {
    return gunAngle;
  }
  public void setGunAngle(Integer gunAngle) {
    this.gunAngle = gunAngle;
  }
  public ModelDefaultState life(Integer life) {
    this.life = life;
    return this;
  }

  

  /**
  * Get life
  * @return life
  **/
  @Schema(description = "")
  public Integer getLife() {
    return life;
  }
  public void setLife(Integer life) {
    this.life = life;
  }
  public ModelDefaultState x(Integer x) {
    this.x = x;
    return this;
  }

  

  /**
  * Get x
  * @return x
  **/
  @Schema(description = "")
  public Integer getX() {
    return x;
  }
  public void setX(Integer x) {
    this.x = x;
  }
  public ModelDefaultState y(Integer y) {
    this.y = y;
    return this;
  }

  

  /**
  * Get y
  * @return y
  **/
  @Schema(description = "")
  public Integer getY() {
    return y;
  }
  public void setY(Integer y) {
    this.y = y;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelDefaultState modelDefaultState = (ModelDefaultState) o;
    return Objects.equals(this.angle, modelDefaultState.angle) &&
        Objects.equals(this.gunAngle, modelDefaultState.gunAngle) &&
        Objects.equals(this.life, modelDefaultState.life) &&
        Objects.equals(this.x, modelDefaultState.x) &&
        Objects.equals(this.y, modelDefaultState.y);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(angle, gunAngle, life, x, y);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelDefaultState {\n");
    
    sb.append("    angle: ").append(toIndentedString(angle)).append("\n");
    sb.append("    gunAngle: ").append(toIndentedString(gunAngle)).append("\n");
    sb.append("    life: ").append(toIndentedString(life)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
