/*
 * Robolucha API
 * Robolucha API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ModelUpdateLuchadorResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-08-05T15:54:58.632Z[GMT]")public class ModelUpdateLuchadorResponse {

  @SerializedName("errors")
  private List<String> errors = null;

  @SerializedName("luchador")
  private ModelGameComponent luchador = null;
  public ModelUpdateLuchadorResponse errors(List<String> errors) {
    this.errors = errors;
    return this;
  }

  public ModelUpdateLuchadorResponse addErrorsItem(String errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<String>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
  * Get errors
  * @return errors
  **/
  @Schema(description = "")
  public List<String> getErrors() {
    return errors;
  }
  public void setErrors(List<String> errors) {
    this.errors = errors;
  }
  public ModelUpdateLuchadorResponse luchador(ModelGameComponent luchador) {
    this.luchador = luchador;
    return this;
  }

  

  /**
  * Get luchador
  * @return luchador
  **/
  @Schema(description = "")
  public ModelGameComponent getLuchador() {
    return luchador;
  }
  public void setLuchador(ModelGameComponent luchador) {
    this.luchador = luchador;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelUpdateLuchadorResponse modelUpdateLuchadorResponse = (ModelUpdateLuchadorResponse) o;
    return Objects.equals(this.errors, modelUpdateLuchadorResponse.errors) &&
        Objects.equals(this.luchador, modelUpdateLuchadorResponse.luchador);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(errors, luchador);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelUpdateLuchadorResponse {\n");
    
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    luchador: ").append(toIndentedString(luchador)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
